# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dawwgs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dawwgs
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'Firebase/Database'
  platform :ios, '8.0'

  target 'DawwgsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DawwgsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
